# Generated by Django 2.1.4 on 2019-01-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
