# Generated by Django 2.1.4 on 2019-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_words', '0002_words_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
