# Generated by Django 2.1.4 on 2019-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_words', '0003_auto_20190119_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lastTweet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
