# Generated by Django 2.1.4 on 2019-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_words', '0004_users_lasttweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='imgUrl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
